# Optuna Hyperparameter Tuning Space Configuration
# Define the search space for hyperparameter optimization

# Model Architecture Parameters
model:
  hidden_channels:
    type: "categorical"
    choices: [32, 64, 128, 256]
  
  kernel_size:
    type: "categorical" 
    choices: [(1, 3), (3, 3), (5, 5)]
  
  dropout:
    type: "uniform"
    low: 0.1
    high: 0.7

# Training Hyperparameters
training:
  learning_rate:
    type: "loguniform"
    low: 0.00001
    high: 0.01
  
  weight_decay:
    type: "loguniform"
    low: 0.00001
    high: 0.1
  
  batch_size:
    type: "categorical"
    choices: [4, 8, 16, 32]
  
  epochs: 100  # Fixed epochs for tuning (not tunable)

# Data Parameters (fixed - not tuned)
data:
  test_size: 0.3

# Tuning Configuration
tuning:
  n_trials: 50
  timeout: 3600  # 1 hour timeout
  direction: "minimize"  # minimize MAE
  metric: "val_mae"  # target metric for optimization
  pruner: "median"  # pruning strategy
  sampler: "tpe"  # sampling strategy
