# ConvLSTM Training Configuration
# Default hyperparameters for training the gripper touch localization model

# Model Architecture
hidden_channels: 64
kernel_size: [1, 3]
dropout: 0.5

# Training Hyperparameters
epochs: 250
batch_size: 8
learning_rate: 0.0001
weight_decay: 0.001

# Data Split
test_size: 0.3